Repository Ssong-Q/OpenMind, pull requests merged in 2023-11, with the labels that each got.

#1 feat: InputTextArea 기능 추가
  src/components/common/InputTextArea/InputTextArea.jsx
  src/components/common/InputTextArea/StyleInputTextArea.js
Labels: ✅feature

#2 feat: ButtonShare 컴포넌트 추가
  src/components/containers/ButtonShare/ButtonShare.jsx
  src/components/containers/ButtonShare/StyleButtonShare.js
  src/components/index.js
  src/style/StyleGlobal.js
Labels: ✅feature

#3 feat: ButtonBadge 기능 추가
  src/components/common/ButtonBadge/CompleteBadge.jsx
  src/components/common/ButtonBadge/IncompleteBadge.jsx
  src/components/common/ButtonBadge/StyleButtonBadge.js
Labels: ✅feature

#4 chore: input에서 textarea로 변경, boolean값 string으로 변경
  src/components/common/InputTextArea/InputTextArea.jsx
  src/components/common/InputTextArea/StyleInputTextArea.js
Labels: 🛠refactor

#5 feat: PageButton 컴포넌트 추가
  public/index.html
  src/components/common/PageButton/PageButton.jsx
  src/components/index.js
Labels: ✅feature

#9 feat: DropDown 요소별 컴포넌트 추가
  src/assets/icon/arrow-down.svg
  src/assets/icon/arrow-up.svg
  src/components/common/DropDown/DropDown.jsx
  src/components/common/DropDown/StyleDropDown.js
  src/components/common/PopOverSort/PopOverSort.jsx
  src/components/common/PopOverSort/StylePopOverSort.js
  src/components/index.js
  src/style/StyleGlobal.js
Labels: ✅feature

#10 feat: DropDown 컴포넌트 완성
  src/components/common/DropDownList/DropDownList.jsx
  src/components/common/DropDownList/StyleDropDownList.js
  src/components/containers/DropDown/DropDown.jsx
  src/components/containers/DropDown/StyleDropDown.js
  src/components/index.js
Labels: ✅feature

#12 feat: ButtonEdit 컴포넌트 추가
  src/assets/icon/edit.svg
  src/components/common/ButtonEdit/ButtonEdit.jsx
  src/components/common/ButtonEdit/StyleButtonEdit.js
  src/components/index.js
Labels: ✅feature

#13 feat: 홈페이지 기능 구현 및 완성
  src/api/api.js
  src/components/common/ButtonBox/ButtonBox.jsx
  src/components/common/ButtonBox/ButtonBoxWithArrow.jsx
  src/components/common/ButtonShare/ButtonShare.jsx
  src/components/common/ButtonShare/StyleButtonShare.js
  src/components/common/InputField/InputField.jsx
  src/components/common/InputField/StyleInputField.js
  src/components/containers/DropDown/DropDown.jsx
  src/components/containers/NavBar/NavBar.jsx
  src/components/containers/NavBar/StyleNavBar.js
  src/components/index.js
  src/pages/HomePage.jsx
  src/pages/StyleHomePage.js
  src/utils/function.js
Labels: ✅feature

#14 feat: ToastButton, like & hate button 추가
  src/components/common/ReactionButton/StyleThumbsButton.js
  src/components/common/ReactionButton/ThumbsDownDown.jsx
  src/components/common/ReactionButton/ThumbsUpButton.jsx
  src/components/common/ToastButton/StyleToastButton.js
  src/components/containers/ReactionCount/ReactionCount.jsx
  src/components/containers/ReactionCount/StyleReactionCount.js
Labels: ✅feature

#15 refactor: 홈페이지 레이아웃 및 스타일 수정
  src/assets/two-guys-image.png
  src/components/containers/NavBar/StyleNavBar.js
  src/pages/HomePage.jsx
  src/pages/StyleHomePage.js
Labels: 🛠refactor

#18 feat : QuestionBox 추가
  src/assets/icon/thumbs-down.svg
  src/assets/icon/thumbs-up.svg
  src/assets/no-question.svg
  src/components/common/QuestionBox/QuestionBox.jsx
  src/components/common/QuestionBox/Style.QuestionBox.js
  src/components/containers/QuestionList/QuestionList.jsx
  src/components/index.js
Labels: ✅feature

#19 feat: post 페이지 헤더 구현
  src/assets/logo.svg
  src/assets/twoguys-image-half.svg
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/containers/PostHeader/PostHeader.jsx
  src/components/containers/PostHeader/StylePostHeader.js
  src/style/StyleGlobal.js
Labels: ✅feature, 🛠refactor, 👾Bug

#21 fix: PostHeader 헤더 구현 및 오류 수정
  src/components/containers/PostHeader/PostHeader.jsx
  src/components/containers/PostHeader/StylePostHeader.js
  src/components/index.js
Labels: ✅feature, 🛠refactor, 👾Bug

#22 feat: 질문 목록 페이지 CardSection 기능 구현
  src/api/api.js
  src/assets/two-guys-home.svg
  src/assets/two-guys-image.png
  src/components/common/ButtonBox/StyleButtonBox.js
  src/components/common/DropDownList/DropDownList.jsx
  src/components/common/DropDownList/StyleDropDownList.js
  src/components/common/InputField/StyleInputField.js
  src/components/common/PageButton/Pagination.jsx
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/containers/DropDown/DropDown.jsx
  src/components/containers/DropDown/StyleDropDown.js
  src/components/containers/NavBar/NavBar.jsx
  src/components/containers/NavBar/StyleNavBar.js
  src/components/containers/PostHeader/StylePostHeader.js
  src/components/containers/UserCard/StyleUserCard.js
  src/components/containers/UserCard/UserCard.jsx
  src/components/containers/UserCard/UserCardSection.jsx
  src/components/index.js
  src/hooks/useWindowSize.js
  src/pages/HomePage.jsx
  src/pages/QuestionListPage.jsx
  src/pages/StyleHomePage.js
  src/pages/StyleQuestionListPage.js
Labels: ✅feature, 🛠refactor, 👾Bug

#23 feat: ButtonShare 컴포넌트 SNS 공유 기능 구현
  public/index.html
  src/components/common/ButtonShare/ButtonShare.jsx
  src/components/common/ButtonShare/StyleButtonShare.js
  src/components/containers/PostHeader/PostHeader.jsx
  src/utils/shareSNS.js
Labels: ✅feature

#24 feat: 질문 목록 페이지 기능 구현 완료(Pagination 추후 보완 예정)
  src/assets/spinner.png
  src/components/common/PageButton/Pagination.jsx
  src/components/common/PageButton/StylePageButton.js
  src/components/containers/Modal/Modal.js
  src/components/containers/Modal/ModalListPage.jsx
  src/components/containers/Modal/ModalLoading.jsx
  src/components/containers/NavBar/NavBar.jsx
  src/components/containers/NavBar/StyleNavBar.js
  src/components/containers/UserCard/StyleUserCard.js
  src/components/containers/UserCard/UserCard.jsx
  src/components/containers/UserCard/UserCardSection.jsx
  src/components/index.js
  src/hooks/useAsync.js
  src/pages/HomePage.jsx
  src/pages/QuestionListPage.jsx
  src/pages/StyleQuestionListPage.js
  src/utils/localStorage.js
Labels: ✅feature, 🛠refactor, 👾Bug

#26 feat: QuestionModal 기능 구현
  src/api/api.js
  src/components/common/InputTextArea/InputTextArea.jsx
  src/components/common/InputTextArea/StyleInputTextArea.js
  src/components/common/ModalQuestionTItle/ModalQuestionTItle.jsx
  src/components/common/ModalQuestionTItle/StyleModalQuestionTitle.js
  src/components/containers/Modal/Modal.js
  src/components/containers/Modal/WriteQuestionModal.jsx
  src/components/index.js
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/StyleFeedPage.js
Labels: ✅feature

#27 fix: Post 헤더와 메인 겹침 현상 해결
  src/components/common/Toast/StyleToast.js
  src/components/containers/PostHeader/PostHeader.jsx
  src/components/containers/PostHeader/StylePostHeader.js
  src/pages/StyleFeedPage.js
Labels: 👾Bug

#29 feat: 링크 복사 후 Toast 5초 보이다 사라지는 기능 구현
  src/components/common/ButtonShare/ButtonShare.jsx
  src/components/common/ButtonShare/StyleButtonShare.js
  src/components/common/Toast/StyleToast.js
  src/components/common/Toast/Toast.jsx
Labels: ✅feature

#32 feat: AnswerPage 2차 중간 push; 질문 불러오기, profile 불러오기, 답변 등록 및 수정 구현 완료
  src/api/api.js
  src/components/containers/AnswerForm/AnswerInputForm.jsx
  src/components/containers/AnswerForm/StyleAnswerForm.js
  src/components/containers/FeedCard/AnswerFeedCard.jsx
  src/components/containers/FeedCard/FeedCardSection.jsx
  src/components/containers/FeedCard/StyleAnswerFeedCard.js
  src/pages/AnswerFeedPage.jsx
Labels: ✅feature, 👾Bug

#33 feat: PostHeader 컴포넌트에서 subject 정보 받아와서 프로필 적용해주는 기능 구현
  src/components/containers/PostHeader/PostHeader.jsx
  src/pages/AnswerFeedPage.jsx
Labels: ✅feature, 🛠refactor

#34 feat: Not Found Page 구현
  src/pages/NotFoundPage.jsx
  src/pages/StyleNotFoundPage.js
Labels: ✅feature

#36 fix: Homepage InputField 사파리 호환 문제 해결
  src/components/common/InputField/StyleInputField.js
Labels: 👾Bug

#37 Feat: AnswerPage 3차 중간 push; 상태에 따른 버튼 text, css 조건부 구현, 무한 스크롤 1차 draft 구현
  public/index.html
  src/api/api.js
  src/assets/icon/thumbs-down.svg
  src/assets/icon/thumbs-up.svg
  src/components/common/ButtonEdit/ButtonEdit.jsx
  src/components/common/ButtonEdit/StyleButtonEdit.js
  src/components/common/ReactionButton/StyleThumbsButton.js
  src/components/common/ReactionButton/ThumbsDownDown.jsx
  src/components/common/ReactionButton/ThumbsUpButton.jsx
  src/components/containers/AnswerForm/AnswerInputForm.jsx
  src/components/containers/AnswerForm/StyleAnswerForm.js
  src/components/containers/FeedCard/AnswerFeedCard.jsx
  src/components/containers/Modal/Modal.js
  src/components/containers/Modal/ModalLoading.jsx
  src/pages/AnswerFeedPage.jsx
  src/pages/StyleAnswerFeedPage.js
Labels: ✅feature, 🛠refactor

#38 Feet: AnswerPage 4차 push; 반응형 구현 및 기타 등등
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/containers/AnswerForm/AnswerForm.jsx
  src/components/containers/AnswerForm/StyleAnswerForm.js
  src/components/containers/FeedCard/StyleFeedCardSection.js
  src/components/containers/Modal/ModalListPage.jsx
  src/components/containers/Modal/WriteQuestionModal.jsx
  src/pages/QuestionListPage.jsx
  src/pages/StyleAnswerFeedPage.js
Labels: ✅feature, 🛠refactor, 👾Bug

#39 Feat: QuestionFeedPage 및 WriteQuestionModal 리팩토링 완료
  src/components/common/ModalQuestionTItle/ModalQuestionTItle.jsx
  src/components/common/ModalQuestionTItle/StyleModalQuestionTitle.js
  src/components/common/NoQuestionBox/NoQuestionBox.jsx
  src/components/common/NoQuestionBox/Style.NoQuestionBox.js
  src/components/common/QuestionBox/QuestionBox.jsx
  src/components/common/QuestionBox/Style.QuestionBox.js
  src/components/containers/FeedCard/AnswerFeedCard.jsx
  src/components/containers/FeedCard/FeedCard.jsx
  src/components/containers/FeedCard/FeedCardSection.jsx
  src/components/containers/FeedCard/QuestionFeedCardSection.jsx
  src/components/containers/FeedCard/StyleFeedCardSection.js
  src/components/containers/Modal/Modal.js
  src/components/containers/Modal/WriteQuestionModal.jsx
  src/components/containers/PostHeader/PostHeader.jsx
  src/components/containers/QuestionList/QuestionList.jsx
  src/components/index.js
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/StyleAnswerFeedPage.js
  src/pages/StyleFeedPage.js
Labels: ✅feature, 🛠refactor

#40 Feat: QuestionFeedPage 좋아요, 싫어요 적용 및 리팩토링 완료
  src/components/containers/FeedCard/FeedCard.jsx
  src/components/containers/Modal/WriteQuestionModal.jsx
  src/pages/QuestionFeedPage.jsx
Labels: ✅feature, 🛠refactor

#42 feat: useModal로 상태관리, modal 컴포넌트 통합, cursor:point , button active 기능 추가
  src/api/api.js
  src/assets/icon/user-setting.png
  src/components/common/AccountDelete/AccountDelete.jsx
  src/components/common/AccountDelete/StyleAccountDelete.js
  src/components/common/DropDownList/DropDownList.jsx
  src/components/common/InputField/InputField.jsx
  src/components/common/InputImage/InputImage.jsx
  src/components/common/InputImage/StyleInputImage.js
  src/components/common/ModalQuestionTItle/ModalQuestionTItle.jsx
  src/components/common/ModalQuestionTItle/StyleModalQuestionTitle.js
  src/components/common/PageButton/Pagination.jsx
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/common/ReactionButton/ThumbsDownDown.jsx
  src/components/common/ReactionButton/ThumbsUpButton.jsx
  src/components/containers/AccountForm/AccountForm.jsx
  src/components/containers/AccountForm/StyleAccountForm.js
  src/components/containers/CheckAccount/CheckAccount.jsx
  src/components/containers/CheckAccount/StyleCheckAccount.js
  src/components/containers/DropDown/DropDown.jsx
  src/components/containers/Modal/Modal.jsx
  src/components/containers/Modal/ModalLoading.jsx
  src/components/containers/Modal/StyleModal.js
  src/components/containers/Modal/WriteQuestionModal.jsx
  src/components/containers/NavBar/NavBar.jsx
  src/components/containers/PostHeader/PostHeader.jsx
  src/components/containers/WriteQuestion/StyleWriteQuestion.js
  src/components/containers/WriteQuestion/WriteQuestionModal.jsx
  src/components/index.js
  src/hooks/index.js
  src/hooks/useAsync.js
  src/hooks/useModal.jsx
  src/hooks/useWindowSize.js
  src/pages/AnswerFeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/QuestionListPage.jsx
Labels: ✅feature, 🛠refactor, 👾Bug

#43 feat: More 컴포넌트 질문삭제, 답변삭제, 답변거절 구현
  src/api/api.js
  src/components/common/DropDownList/MoreMenu.jsx
  src/components/common/DropDownList/StyleDropDownList.js
  src/components/containers/FeedCard/AnswerFeedCard.jsx
  src/components/containers/FeedCard/FeedCard.jsx
  src/components/containers/FeedCard/FeedCardSection.jsx
  src/components/containers/More/More.jsx
  src/components/containers/More/StyleMore.js
  src/components/index.js
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
Labels: ✅feature, 🛠refactor

#44 Feat: 질문 목록 리스트 페이지네이션 Link 구현, 드롭다운 outsideClick 리팩토링
  src/Main.jsx
  src/components/common/ButtonEdit/ButtonEdit.jsx
  src/components/common/ButtonEdit/StyleButtonEdit.js
  src/components/common/DropDownList/StyleDropDownList.js
  src/components/common/PageButton/Pagination.jsx
  src/components/common/PageButton/StylePageButton.js
  src/components/containers/DropDown/DropDown.jsx
  src/components/containers/DropDown/StyleDropDown.js
  src/components/containers/Modal/StyleModal.js
  src/components/containers/WriteQuestion/StyleWriteQuestion.js
  src/components/containers/WriteQuestion/WriteQuestionModal.jsx
  src/hooks/index.js
  src/hooks/useModal.js
  src/pages/HomePage.jsx
  src/pages/QuestionListPage.jsx
Labels: ✅feature, 🛠refactor

#45 feat: More 컴포넌트 케밥 외 클릭시 자동 닫히기 기능 추가 및 기타 스타일 수정
  src/components/common/ButtonBadge/StyleButtonBadge.js
  src/components/common/DropDownList/MoreMenu.jsx
  src/components/common/DropDownList/StyleDropDownList.js
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/containers/AnswerForm/StyleAnswerForm.js
  src/components/containers/More/More.jsx
  src/components/containers/PostHeader/PostHeader.jsx
  src/style/StyleGlobal.js
Labels: ✅feature, 🛠refactor, 👾Bug

#46 feat: 페이지에 따른 pagination 컴포넌트 변화 구현
  src/components/common/PageButton/Pagination.jsx
  src/components/common/PageButton/StylePageButton.js
  src/components/common/PageButton/getPageArray.js
  src/pages/QuestionListPage.jsx
  src/pages/StyleNotFoundPage.js
Labels: ✅feature, 👾Bug

#47 feat: 페이지에 따른 pagination 컴포넌트 변화 구현
  src/components/common/PageButton/Pagination.jsx
  src/components/common/PageButton/createPageArray.js
Labels: ✅feature, 🛠refactor, 👾Bug

#48 Refactor: 질문 목록 페이지 리팩토링
  src/components/common/ModalQuestionTItle/StyleModalQuestionTitle.js
  src/components/common/PageButton/Pagination.jsx
  src/components/common/PageButton/createPageArray.js
Labels: 🛠refactor

#49 fix: Arrow 아이콘 클릭시 DropDownList 열리지 않는 오류 수정
  src/components/containers/DropDown/DropDown.jsx
Labels: 👾Bug

#50 design : accountCheck modal style , post header profileImage hover수정
  src/components/common/ModalQuestionTItle/ModalQuestionTItle.jsx
  src/components/common/ModalQuestionTItle/StyleModalQuestionTitle.js
  src/components/common/PageButton/Pagination.jsx
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/containers/CheckAccount/StyleCheckAccount.js
  src/components/containers/Modal/Modal.jsx
  src/components/containers/Modal/StyleModal.js
  src/components/containers/PostHeader/PostHeader.jsx
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/QuestionListPage.jsx
Labels: 🛠refactor

#52 Refactor: HomePage 리팩토링
  src/assets/icon/arrow-right.svg
  src/assets/icon/person.svg
  src/components/common/ReactionButton/StyleThumbsButton.js
  src/components/containers/NavBar/StyleNavBar.js
Labels: 🛠refactor, 👾Bug

#55 feat: QuestionListPage 최신순, 이름순의 정렬에 따라 params 변경
  src/Main.jsx
  src/components/common/DropDownList/DropDownList.jsx
  src/components/common/PageButton/Pagination.jsx
  src/components/containers/DropDown/DropDown.jsx
  src/pages/HomePage.jsx
  src/pages/QuestionListPage.jsx
Labels: ✅feature

#56 style: christmas theme background, button 색상 변경
  package-lock.json
  package.json
  src/assets/christmas-background.png
  src/assets/santa.svg
  src/components/App.jsx
  src/components/common/ButtonBox/ButtonBox.jsx
  src/components/common/ButtonBox/StyleButtonBox.js
  src/components/common/NoQuestionBox/NoQuestionBox.jsx
  src/components/common/PageButton/StylePageButton.js
  src/components/containers/AccountForm/StyleAccountForm.js
  src/components/containers/FeedCard/FeedCardSection.jsx
  src/components/containers/Modal/ModalListPage.jsx
  src/components/containers/PostHeader/StylePostHeader.js
  src/components/index.js
  src/index.jsx
  src/pages/StyleFeedPage.js
  src/pages/StyleHomePage.js
  src/style/StyleGlobal.js
  src/style/theme.js
Labels: ✅feature

#57 feat: 크리스마스 테마 로고 구현 및 무한스크롤 오류 수정
  src/api/api.js
  src/assets/christmas-logo.png
  src/components/containers/NavBar/NavBar.jsx
  src/components/containers/PostHeader/PostHeader.jsx
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/StyleHomePage.js
Labels: ✅feature, 🛠refactor, 👾Bug

#58 style: christams theme 추가
  src/assets/icon/christmas-leaf.svg
  src/components/common/NoQuestionBox/NoQuestionBox.jsx
  src/components/containers/FeedCard/FeedCardSection.jsx
  src/components/containers/FeedCard/QuestionFeedCardSection.jsx
  src/components/containers/QuestionList/QuestionList.jsx
  src/components/containers/UserCard/UserCard.jsx
  src/components/containers/WriteQuestion/StyleWriteQuestion.js
  src/components/index.js
  src/style/theme.js
Labels: 🛠refactor

#59 Feat: HomePage Theme toggle 기능 구현
  src/assets/icon/arrow-right-brown.svg
  src/assets/icon/arrow-right-white.svg
  src/components/App.jsx
  src/components/common/ButtonBox/ButtonBoxWithArrow.jsx
  src/components/common/ButtonBox/StyleButtonBox.js
  src/components/common/Toggle/StyleToggle.js
  src/components/common/Toggle/Toggle.jsx
  src/components/containers/NavBar/NavBar.jsx
  src/components/containers/PostHeader/PostHeader.jsx
  src/components/index.js
  src/pages/AnswerFeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/QuestionFeedPage.jsx
  src/style/StyleGlobal.js
  src/style/theme.js
Labels: ✅feature, 🛠refactor

#60 fix: FeedCardSection 컴포넌트 console.log(theme) 제거
  src/components/containers/FeedCard/FeedCardSection.jsx
Labels: 🛠refactor

#62 fix: onKeyPress 삭제, InputField placeholder 수정
  src/components/common/InputField/InputField.jsx
Labels: 🛠refactor

#64 refactor: QuestionPage에서는 계정 관리 모달 못 띄우게 만듬
  src/components/containers/PostHeader/PostHeader.jsx
Labels: 🛠refactor

#65 Create README.md
  README.md
Labels: 📄Document

#67 refactor: 무한스크롤 방식 변경
  public/_redirects
  src/api/infiniteScroll.js
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/StyleFeedPage.js
Labels: ✅feature, 🛠refactor

#68 refactor: QuestionListPage sort 쿼리 스트링 리팩토링
  src/pages/QuestionListPage.jsx
Labels: 🛠refactor

#69 Merge: Develop to main (Refactor 사항 반영)
  public/_redirects
  src/components/common/InputField/InputField.jsx
  src/components/containers/PostHeader/PostHeader.jsx
  src/pages/AnswerFeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/QuestionListPage.jsx
  src/pages/StyleFeedPage.js
  src/pages/StyleNotFoundPage.js
  src/utils/localStorage.js
Labels: ✅feature, 🛠refactor, 👾Bug

#70 fix: main merge 시 꼬인거 fix
  src/api/infiniteScroll.js
  src/components/common/InputField/InputField.jsx
  src/pages/NotFoundPage.jsx
  src/pages/StyleFeedPage.js
  src/pages/StyleNotFoundPage.js
  src/utils/localStorage.js
Labels: 👾Bug

#71 refactor: error handling 및 무한스크롤 무한통신 에러 수정
  src/components/common/ButtonShare/ButtonShare.jsx
  src/components/common/ReactionButton/ParticleButton.jsx
  src/components/common/ReactionButton/StyleParticleButton.js
  src/components/common/Toast/Toast.jsx
  src/pages/AnswerFeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/QuestionListPage.jsx
  src/utils/shareSNS.js
Labels: 🛠refactor, 👾Bug

#73 add content to README.md
  README.md
Labels: 📄Document

#75 fix: HomePage 모바일 사이즈에서 토글 display
  src/components/App.jsx
  src/components/common/Toggle/StyleToggle.js
  src/components/common/Toggle/Toggle.jsx
  src/pages/HomePage.jsx
Labels: 🛠refactor

#76 Merge: Develop to main (Refactor 사항 반영)
  src/api/infiniteScroll.js
  src/components/App.jsx
  src/components/common/ButtonShare/ButtonShare.jsx
  src/components/common/InputField/InputField.jsx
  src/components/common/ProfileImage/StyleProfileImage.js
  src/components/common/ReactionButton/ParticleButton.jsx
  src/components/common/ReactionButton/StyleParticleButton.js
  src/components/common/Toast/Toast.jsx
  src/components/common/Toggle/StyleToggle.js
  src/components/common/Toggle/Toggle.jsx
  src/pages/AnswerFeedPage.jsx
  src/pages/HomePage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/QuestionFeedPage.jsx
  src/pages/QuestionListPage.jsx
  src/pages/StyleFeedPage.js
  src/pages/StyleNotFoundPage.js
  src/utils/localStorage.js
  src/utils/shareSNS.js
Labels: ✅feature, 🛠refactor, 👾Bug

#77 fix: main merge 후 이상하게 중복된 부분 fix
  src/pages/AnswerFeedPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/QuestionFeedPage.jsx
Labels: 👾Bug

#78 fix: 테마 토글 일원화하여 모바일에서 상태 반영 오류 해결
  src/components/common/Toggle/StyleToggle.js
  src/components/common/Toggle/Toggle.jsx
  src/components/containers/NavBar/NavBar.jsx
  src/pages/HomePage.jsx
Labels: 👾Bug

#79 refactor: FeedPage 초기 데이터 가져오도록 수정
  src/pages/AnswerFeedPage.jsx
  src/pages/QuestionFeedPage.jsx
Labels: 🛠refactor

#80 fix: AnswerPage 아규먼트 수정
  src/pages/AnswerFeedPage.jsx
Labels: 👾Bug

#81 feat: Toast 메시지 사라질 때 fadeout 애니메이션 효과 추가
  src/components/common/Toast/StyleToast.js
Labels: ✅feature, 🛠refactor
